### ISSUE TITLE
HRESULT: 0x800706BA Error

### ISSUE THREAD

**Issue by pepa140** [mscrivo/OotD#116]
I´m running Outlook on the Desktop. Than I run MS Outlook and when I close it, also the core of MS Outlook, which is requied for the app to run, turns off. Than the OotD freezes and than when i click Exit i see this pop-up: 
![pop-up](https://user-images.githubusercontent.com/44846200/48149578-bdbfe900-e2bc-11e8-9df7-dc77789f0e1a.JPG)

I have Windows 7 64x
MS Outlook 2010
Outlook on the Desktop 3.7.0

**Comment by mscrivo** [comment]
When you say you close the core of MS Outlook, are you doing that via the tray icon?  If so, then this is expected behaviour.  OotD cannot run without that running.  You are not meant to close it.  When OotD is closed, it will clean that up.  I could make this more robust I suppose and detect when that happens and try to restart it.

**Comment by mscrivo** [comment]
Oh I see .. Outlook itself is closing the Outlook engine upon closing.  This is new behaviour, I'll see if I can fix it.  Thank

**Comment by mscrivo** [comment]
3.7.5 has a fix for this.  Thanks for reporting it!

**Comment by pepa140** [comment]
Thank you for the repair :)
