### ISSUE TITLE
There was an error initializing the application:

### ISSUE THREAD

**Issue by cowboytechy** [mscrivo/OotD#51]
![image](https://cloud.githubusercontent.com/assets/19369451/15272263/c2dc0d16-1a36-11e6-8a1d-0c3295205517.png)

**Comment by saimukund** [comment]
![image](https://cloud.githubusercontent.com/assets/17783042/15354302/8c0a68ba-1d0a-11e6-8e47-7461c63c1ddc.png)

**Comment by mscrivo** [comment]
Interesting, what versions of Office are you both running?

**Comment by saimukund** [comment]
I am using MS office 2013.

On Sun, Jun 26, 2016 at 12:13 AM, Michael Scrivo <notifications@github.com>
wrote:

> Interesting, what versions of Office are you both running?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mscrivo/ootd/issues/51#issuecomment-228564320>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AQ9ZAhUGMtQPBaklGFc6p9vf_yyVRUZaks5qPXbEgaJpZM4Iew5M>
> .
>



-- 
Regards,
Mukund

**Comment by cowboytechy** [comment]
Using 2013 ProPlus x86 on a x64 Windows 10 system.....using x86 because my Quicken does not sync reminders with x64 version only an x86 version!!!

**Comment by willshattuck** [comment]
Hi,

I just downloaded 3.5 OotD and I am also getting this error.  I uninstalled and tried earlier versions all the way back to 1.6 since I have Outlook 2010.

My installation consists of Office 2010 and Office 2013.  I do not have Outlook 2013 installed.  I don't like that interface.  I don't think this is causing it, but I am not familiar with .NET error messages.  I did have an older version of OotD running, but uninstalled it as I wasn't using it.  Now my job changed and getting Outlook on my Desktop would be convenient. : ) 

Any suggestions on howto resolve the error message?
![outlook on the desktop startup error](https://cloud.githubusercontent.com/assets/157313/21939677/c251876e-d975-11e6-9388-375a2af2bc0b.jpg)

**Comment by willshattuck** [comment]
I did a BUNCH of searching and found this website article.

https://www.fieldstonsoftware.com/support/support_gsyncit_8002801D.shtml

I had both the 9.4 and 9.5 keys in the Step 2 section.  By deleting 9.5 Outlook on the Desktop was able to start.

**Comment by mscrivo** [comment]
wow, that's some great digging!  Thanks for finding that.

**Comment by willshattuck** [comment]
You're very welcome.  With my change in workflow (more projects, less email interaction) OotD let's me see my email every time I change programs.  Thanks for the great piece of software.

**Comment by mscrivo** [comment]
I've added that link to the FAQ.  I've also found that in really exception cases.  Uninstalling office and running the [office cleanup tool](https://support.office.com/en-us/article/Uninstall-Office-2016-Office-2013-or-Office-365-from-a-PC-9dd49b83-264a-477a-8fcc-2fdf5dbf61d8), then rebooting and reinstalling Office, usually fixes these startup issues as well.
