### ISSUE TITLE
OotD not showing on main screen

### ISSUE THREAD

**Issue by ManleyRunner** [mscrivo/OotD#59]
I typically leave the app on my other (2nd) monitor when at my desk, but when I am traveling or not using two screens, I do not see the app on the laptop.  Does anyone have this issue?

**Comment by mscrivo** [comment]
OotD does not auto-adjust for situations where monitor configurations change.  You'll have to move it to your laptop screen manually to achieve this.  The reason I can't auto move it over is because the settings use absolute positions to allow people to arrange them on their desktop exactly how they want them.  It's not your typical app, where you can just move it to the other screen and maximize it and you're done.
