### ISSUE TITLE
Calendar overlay view

### ISSUE THREAD

**Issue by GoodKey** [mscrivo/OotD#61]
I'd love to be able to overlay my different calendars like in outlook. As far is I understand this is not possible yet, which makes the tool only useful for people with a single calendar. I use different calendars for different things: school, leisure time, etc.

**Comment by mscrivo** [comment]
yeah unfortunately, it's not clear if that's even possible with the Outlook View control that OotD uses.  The best you can do for now is just have separate instances showing each calendar separately.

**Comment by TLFulton** [comment]
I agree that this is a much needed feature. For now, the only work around is I had to make another calendar and copy all my other calendars into it in list view. It sucks because I can't color coordinate the calendars and they don't auto update. This is an important feature that should be added to the next upgrade. Other than that, I love the program.

**Comment by TLFulton** [comment]
I found the fix! It's a free Outlook addon from CodeTwo that will merge and sync all of your (user selected) Outlook calendars into one (or however many you want). The only downside is you have to color coordinate them manually, but it's not that difficult to do in list view. I'm following this thread, if you have questions, ask. Here is the link to the addon: https://www.codetwo.com/freeware/foldersync-addin/?sts=1646
