### ISSUE TITLE
Filter set in Task view not saved

### ISSUE THREAD

**Issue by smwight** [mscrivo/OotD#83]
When using task view with a filter set the filter is not saved and must be reapplied at next start up

**Comment by agandelman** [comment]
I have same issue. I changed the columns from "Icon>Complete>Subject>Due Date>Categories>Flag Status" to "Complete>Subject>Created>Due Date>Comment" it it reverts back every time the application reopens.

Also, please apply a setting for a global alpha in order to have all instances in same alpha.

Thanks
