### ISSUE TITLE
Outlook On TDT turns white

### ISSUE THREAD

**Issue by dchbbc** [mscrivo/OotD#95]
When I start Outlook On The Desktop my Outlook Program opens and the calendar loads on the desktop fine but if I close my Outlook, the OOTDT turns white. The bar at the top stays but all of the calendar grid and writing is gone. I have to restart it and leave Outlook open minimized. I use Microsoft Office 2016. All up dates on my PC (Windows 10), Outlook are done and I use the latest version of OOTDT. I uninstalled it and reinstalled it also. Any suggestions?

**Comment by mscrivo** [comment]
Yeah something happened in the latest update of Outlook 2016 that changed the behaviour of how it operates in the background.  I'm still trying to figure out if it's a bug, or some new permanent behaviour and if so, how to work around it.  I'm inclined to think it's a bug in Outlook because the 64-bit version is not exhibiting the same behaviour.

**Comment by wvogen** [comment]
I have the same issue . I have uninstalled OOTD and tried several past versions with no luck. Please help this is a good program.

**Comment by mscrivo** [comment]
I'm at the mercy of Microsoft on this one .. will have to wait and see if they fix it.  In the mean time, if installing the 64-bit version of Office is an option, that seems to work fine.

**Comment by mscrivo** [comment]
It seems Microsoft has fixed this in the latest updates for Office 2016, so I'm going to close this.
